In [ ]:
import numpy as np

**Если в задании не сказано иного, допусккается использование любых библиотек.**

## Задача №1 

Посчитайте и верните количество больших и маленьких букв в строке в формате ($N_{больших}$, $N_{маленьких}$).

In [3]:
def string_test(s):
    up = 0
    low = 0
    
    for char in s:
        if 'A' <= char <= 'Z':
            up += 1
        elif 'a' <= char <= 'z':
            low += 1
            
    return (up, low)

In [4]:
# Проверка
assert string_test('The Quick Brown Fox') == (4, 12), "Что-то не так"
print('Всё ОК!')

Всё ОК!


## Задача №2 

Реализуйте функцию стека ([Last in First Out](https://ru.wikipedia.org/wiki/Стек)).

На вход подается список $a$ (текущий стек) и список $b$, содержащий элементы, которые нужно добавить в стек. 

Функция должна возвращать обновленный стек.

In [23]:
def stack(a, b):
    for i in range(len(b)):
        a.append(b[len(b)-1-i])
    return a

In [24]:
# Проверка
assert stack([1, 2, 3], [4, 5]) == [1, 2, 3, 5, 4], "Что-то не так"
print('Всё ОК!')

Всё ОК!


## Задача №3

Реализовать матричное произведение без использования `numpy`.

Функция должна возвращать новую матрицу.

In [51]:
import numpy as np
def matrix_mult(a, b):
    c = np.zeros((len(a), len(b)))
    assert len(a) == len(b[0]), "Матрицы имеют недопустимые размеры"
    for i in range(len(a)):
        for j in range(len(b)):
            for k in range(len(a)):
                c[i][j] += a[i][k]*b[k][j]
    return c

In [53]:
# Проверка
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]
b = [
    [5, 1, 2],
    [2, 3, 1],
    [1, 7, 2]
]
assert (matrix_mult(a, b) == np.array(a) @ np.array(b)).all(), "Что-то не так"
print('Всё ОК!')

[[12. 28. 10.]
 [36. 61. 25.]
 [60. 94. 40.]]
Всё ОК!


# Задача 4

Для заданного числа найдите ближайший к нему элемент в векторе.

In [58]:
def find_closest(lst, num):
    min_ind = 0
    min = 1000000
    for i in range(len(lst)):
        if abs(lst[i] - num) <= min:
            min_ind = i
            min = abs(lst[i] - num)
    return lst[min_ind]

In [59]:
# Проверка
a = -3
b = [-5, 7, 2, 4, -6, 0, 1]
assert find_closest(b, a) == -5, "Что-то не так"
print('Всё ОК!')

Всё ОК!


# Задача 5

Напишите функцию, которая вычисляет оптимальные веса согласно [теореме Гаусса-Маркова](https://ru.wikipedia.org/wiki/Теорема_Гаусса_—_Маркова):

$$\vec{w} = (X^TX)^{-1}X^{T} \vec{y}, $$

где $\vec{w}$ - вектор весов, который вам нужно вычислить,

$X$ - матрица признаков размером $(n\times m)$,

$\vec{y}$ - вектор ответов.

In [60]:
def matrix_mult(a, b):
    c = np.zeros((len(a), len(b)))
    assert len(a) == len(b[0]), "Матрицы имеют недопустимые размеры"
    for i in range(len(a)):
        for j in range(len(b)):
            for k in range(len(a)):
                c[i][j] += a[i][k]*b[k][j]
    return c

def gauss_markov_decision(X, y):
    XX = matrix_multy(X, X.T)
    inv = np.linalg.inv(XX)
    XXX = matrix_multy(inv, X.T)
    return matrix_multy(XXX, y)

In [61]:
# Проверка
import pandas as pd
from sklearn.datasets import load_boston

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
X = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
y = np.array(raw_df.values[1::2, 2])

true_gauss_markov_decision = np.array([-9.28965170e-02, 4.87149552e-02, -4.05997958e-03, 2.85399882e+00,
                                       -2.86843637e+00, 5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
                                       1.71151128e-01, -9.39621540e-03, -3.92190926e-01, 1.49056102e-02,
                                       -4.16304471e-01])

assert np.allclose(gauss_markov_decision(X, y), true_gauss_markov_decision), "Что-то не так"
print('Всё ОК!')

<>:6: SyntaxWarning: invalid escape sequence '\s'
<>:6: SyntaxWarning: invalid escape sequence '\s'
C:\Users\User\AppData\Local\Temp\ipykernel_15472\1296951070.py:6: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
C:\Users\User\AppData\Local\Temp\ipykernel_15472\1296951070.py:6: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)


ModuleNotFoundError: No module named 'sklearn'